### PR TITLE
Fix primary name construction

### PR DESCRIPTION
**Pull request by stoned**
- with the introduction of Documentable::Utils::Text:textify-pod()
a variant of Pod::Utilities::textify-guts()
  - see https://github.com/antoniogamiz/Pod-Utilities/pull/9/files#diff-0ff387c7e4dec76c01cb77aa4d338ee1R5
- as an example, while processing perl6/doc this prevent the generation
of the document '/routine/(<) , infix ⊂' document in favor of
'/routine/(<), infix ⊂'

Also a version bump of Documentable might be worth considering.

### CODE REVIEW

**Comment by JJ** [comment]
I'm sorry, what's the difference between
/routine/(<) , infix ⊂
and
/routine/(<), infix ⊂
?

**Comment by stoned** [comment]
There is an extra space before the comma.
See for example, as of now https://docs.perl6.org/routine/(%3C)%20,%20infix%20%20%E2%8A%82 *and* https://docs.perl6.org/routine/(%3C),%20infix%20%E2%8A%82 And more, both these URL are linked from https://docs.perl6.org/routine.html

**Comment by stoned** [comment]
Sure I can add some tests. The thing is the existing tests in both Pod-Utilities repository and Documentable repository had me wondering for a while on this "issue" ;-).

**Comment by JJ** [comment]
> There is an extra space before the comma.
> See for example, as of now https://docs.perl6.org/routine/(%3C)%20,%20infix%20%20%E2%8A%82 _and_ https://docs.perl6.org/routine/(%3C),%20infix%20%E2%8A%82 And more, both these URL are linked from https://docs.perl6.org/routine.html

Ah, OK. It does not show in markdown. I'd definitely want a test for that...

**Comment by stoned** [comment]
@JJ I have added some tests.

**Pull request merged**
